name:                lattest-lib
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ramon-janssen/lattest
license:             BSD3
author:              Ramon Janssen
copyright:           2023 Ramon Janssen
category:            Testing
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7
  - containers >= 0.6.0.1
  - mtl >= 2.0
  - stm >= 2.1
  - MissingH >= 1.2.0.0
  - bytestring >= 0.10.8.2
  - text >= 1.2.5.0
  - network >= 3.1.2.7
  - io-streams >= 1.4.0.0
  - attoparsec >= 0.14.4
  - attoparsec-data >= 1.0.5.3
  - aeson >= 2.0.0.0
  - attoparsec-aeson >= 2.1.0.0
  - time >= 1.12.2
  - random >= 1.2.1.1
  - extra >= 1.7.14
  - unbounded-delays >= 0.1.1.1
  - either >= 5.0.2
  - lattices >= 2.0.0
  - stm >= 2.5.1.0
  - grisette >= 0.9.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  other-modules: []

# currently no need for a standalone application, 'running' can be done via stack ghci
#executables:
#  lattest-lib:
#    source-dirs:      src
#    main:             Main.hs
#    dependencies:
#    - lattest-lib

tests:
  lattest-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lattest-lib
    - HUnit >= 1.6.2.0
    - QuickCheck < 2.15
    - utf8-string >= 1.0.2
