name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  stack:
    strategy:
      matrix:
        ghcversion: [9.8.4, 9.10.3, 9.12.4]
    name: testsuite

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: ${{ matrix.ghcversion }}
        enable-stack: true
        stack-version: 'latest'

    - name: Restore cached stackwork
      id: cache1
      uses: actions/cache/restore@v4
      env:
        cache-name: cache1
      with:
        path: lattest-lib/.stack-work
        key: stackwork-${{ matrix.ghcversion }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          stackwork-${{ matrix.ghcversion }}-{{ env.cache-name }}-
    - name: Restore cached stackdir
      id: cache2
      uses: actions/cache/restore@v4
      env:
        cache-name: cache2
      with:
        path: ~/.stack
        key: stack-${{ matrix.ghcversion }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          stack-${{ matrix.ghcversion }}-${{ env.cache-name }}-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install z3
        cd lattest-lib
        stack build lattest-lib:lib lattest-lib:test:lattest-test --system-ghc --only-dependencies --stack-yaml "stack-${{ matrix.ghcversion }}.yaml"

    - name: Cache stackwork
      uses: actions/cache/save@v4
      if: steps.cache1.outputs.cache-hit != 'true'
      with:
        path: lattest-lib/.stack-work
        key: ${{ steps.cache1.outputs.cache-primary-key }}
        
    - name: Cache stack
      uses: actions/cache/save@v4
      if: steps.cache2.outputs.cache-hit != 'true'
      with:
        path: ~/.stack
        key: ${{ steps.cache2.outputs.cache-primary-key }}

    - name: Build
      run: |
        cd lattest-lib
        stack build lattest-lib:lib lattest-lib:test:lattest-test --no-run-tests --system-ghc --stack-yaml "stack-${{ matrix.ghcversion }}.yaml"
    - name: Run tests
      run: |
        cd lattest-lib
        stack test --system-ghc --stack-yaml "stack-${{ matrix.ghcversion }}.yaml"
