name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  stack:
    name: stack-lts-23.18

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: '9.8.4'
        enable-stack: true
        stack-version: 'latest'

    - name: Restore cached dependencies
      id: cache
      uses: actions/cache/restore@v4
      env:
        cache-name: cache
      with:
        path: lattest-lib/.stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install z3
        cd lattest-lib
        stack build lattest-lib:lib lattest-lib:test:lattest-test --system-ghc --only-dependencies

    - name: Cache the dependencies
      uses: actions/cache/save@v4
      # if: steps.cache.outputs.cache-hit != 'true'
      with:
        path: lattest-lib/.stack-work
        key: ${{ steps.cache.outputs.cache-primary-key }}

    - name: Build
      run: |
        cd lattest-lib
        stack build lattest-lib:lib lattest-lib:test:lattest-test --system-ghc
    - name: Run tests
      run: |
        cd lattest-lib
        stack test --system-ghc
